from datetime import timedelta
from typing import Optional, Dict, Any

class TokenRepository:
    def save(self, token: str, data: Dict[str, Any], ttl: timedelta): ...
    def get(self, token: str) -> Optional[Dict[str, Any]]: ...
    def delete(self, token: str) -> None: ...
