class FileRepository:
    def list_by_owner(self, owner): ...
    def create(self, owner, meta): ...
    def get(self, owner, fid): ...
    def delete(self, owner, fid): ...
    def update(self, owner, fid, data): ...
