from typing import BinaryIO

class StorageRepository:
    def put(self, key: str, stream: BinaryIO, content_type: str) -> None: ...
    def get_presigned_url(self, key: str, expires_seconds: int = 900) -> str: ...
    def get_object(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...
